### ISSUE TITLE
叫'云存储平台'合适吗？

### ISSUE THREAD

**Issue by sglzs** [sgjsakura/CC98Share#27]
> CC98Share是一个供98用户进行文件上传与分享的云储存平台

请问使用了哪些'云技术'?

叫网盘掉档次吗？

**Comment by MoLan1980** [comment]
前辈你好，技术组已收到反馈，正在修订新的使用条例。
感谢前辈对CC98Share的关注和支持~

**Comment by MoLan1980** [comment]
bug已改，感谢前辈的意见。如果有新的疑问，可以重新打开issue提出~
