### ISSUE TITLE
CC98 Share 后台数据设计

### ISSUE THREAD

**Issue by sgjsakura** [sgjsakura/CC98Share#5]
数据库设计结构讨论。目前而言需要存储的数据库结构为：

文件表，包含用户上传的每个文件，其中包含如下信息：
- 编号（ID）
- 文件名
- 描述
- 实际在服务器上存储的位置
- 上传者
- 是否共享给他人
- 下载次数
- 上传时间

在实际设计中，如果发现功能上需要其他信息，请在此跟帖回复说明详情。

**Comment by wyc-ruiker** [comment]
需要下载次数或者文件热度之类的东西吗？

**Comment by RiotChen** [comment]
那这样是不是还要写个按热度和下载量排序

**Comment by sgjsakura** [comment]
@wyc-ruiker Share 不是软件站啊，共享好像不是核心业务，确定需要这个吗？
@RiotChen 如果添加了下载量的话那要支持排序

**Comment by wyc-ruiker** [comment]
@sgjsakura  恩。。。那就不需要吧

**Comment by sgjsakura** [comment]
@wyc-ruiker 后台还是支持吧，前台暂时不显示这个功能。但统计数据还是记录，以后如果需要的时候再重新统计就不准了。

**Comment by RiotChen** [comment]
考虑增加一个上传时间？    排序比较方便

**Comment by sgjsakura** [comment]
@RiotChen 可以有

**Comment by sgjsakura** [comment]
1.0 项目已完成，如有需要可在 2.0 重新打开
