### ISSUE TITLE
前端页面的设计与搭建

### ISSUE THREAD

**Issue by MoLan1980** [sgjsakura/CC98Share#8]

**Comment by sgjsakura** [comment]
@MoLan1980   目前框架自带的是 bootstrap 和 jquery，如果可以的话尽可能用这个框架？

**Comment by sgjsakura** [comment]
@MoLan1980 全局性的页面除了首页应该还需要一个关于页面？或者也可以合起来……

**Comment by MoLan1980** [comment]
页面需求：
1.	用户登录&首页
2.	用户自己的文件列表页
3.	他人公开分享的文件列表页（可以包含在2中，不同之处就是头像、权限之类的）
4.	单个文件详情页（可以没有。如果要开发在线阅览文件功能的话）
5.	搜索结果页（可包含在2中，搜索框存在于2，3，4中）
6.	关于页面看有多少内容可以展示？比如把版本、版权、问题反馈、帮助中心等融合到一个页面中
@sgjsakura 
最少2个页面，登录页面和详情页面吧

**Comment by sgjsakura** [comment]
@MoLan1980 还有上传需要有一个页面吧，还是和详情页面合并呢？

**Comment by MoLan1980** [comment]
@sgjsakura 上传页面感觉可以直接用一个按钮代替，然后弹出框这样？

**Comment by sgjsakura** [comment]
@MoLan1980 也可以啊，先做出来看看效果吧，从HTML5的角度来说，拖放什么的比较炫酷吧，不过短期内不用太在意……

**Comment by MoLan1980** [comment]
@sgjsakura 拖放的话似乎可以直接监视整个页面，我发现百度网盘有这样的功能。。。然后关于界面，我们不添加一些图标什么的么？直接扁平化&简洁化？以及屏幕尺寸的问题是否要加以考虑（这个我不太会）。

**Comment by sgjsakura** [comment]
@MoLan1980 图标肯定需要呀，关于UI的视觉效果的话自行决定？拖放是HTML5里面的功能，需要JS支持恩……屏幕尺寸的话，如果用bootstrap的话他应该能有基本的设备适配功能，UI结构不复杂的话应该够用

**Comment by MoLan1980** [comment]
@sgjsakura 唔我说那种图片，需要有人来设计的那种_(:з」∠)_，比如share的LOGO，是否需要从编辑部拉一个人，还是用以前的？bootstrap查了些资料，感觉UI方面是一个已经写好了很多样式的集成，添加对应class就好？

**Comment by sgjsakura** [comment]
@MoLan1980 图标什么可以让外援帮忙恩……bootstrap还是比较完善的，不是很复杂的界面需求的话基本够用啦，竞猜中心就是纯bootstrap构建的，没有其他的样式
